#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

dist: xenial
addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - libboost-all-dev
    - libeigen3-dev
    - python-pip
    - python3-pip
    - cython
    - python-nose
    - python-numpy
    - python-coverage
    - cython3
    - python3-nose
    - python3-numpy
    - python3-coverage
    - python3-setuptools
    - libtinyxml2-dev
branches:
  except:
  - debian
language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES=""
  - GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython jrl-umi3218/SpaceVecAlg jrl-umi3218/RBDyn"
  - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON -DPYTHON_BINDING_USER_INSTALL:BOOL=ON"
  matrix:
  - CMAKE_BUILD_TYPE=RelWithDebInfo
  - CMAKE_BUILD_TYPE=Debug
notifications:
  slack:
    secure: GpgEGE5Njo16lq1KkYjbsizEPdI9PzhEMBZhxaMkjTQ2P1iDssZjGzbhIsLqAKJ4/FlvesqHd7k/PyGH6x8y96Q/skfjrgFCd0nLDJm2lQAs7641nIsRdSO0zvQfoBsYm8GxpIw4dJUU9/2gKDv87infaBrOM35Xe4KsCcKiV1hRMVcEOigzASaycxUYcaydMJ5hcFoZ6QKD1UUJ6el/we/ep/qtiB+vIPs92WuW998Zqq3zcH2EisAzyOOCvB+BGiPPTKKfMHAW7t3b7uZ9VFbmWy7vHAtOTcOu4Skc4hli56dWaTAhlKPpaOFF1wMLiTQrUAuzJ4bKtpIdSh4kRKbnuzSrJr8b2LHv06v3qXcCBTsjQNKNjlHNyccJ+S8B08QDYYXlRbtIvpFnR4R3k+P38MA10uv+09fqO8T2Ig1GLyCQcT3GBrcLrB2XR5h9ZfnPWwDYuT1lE2ZyY4UmD97y0EOiq/8cjK3qVdpg9Vsj8bhWwAEp/c5RGAhS3eRw0dPy8zd6J4SnYUd4oQTt6Zs8j4YDDf3A7DceG3+0X3uE31t/6laSu2LJNoPYaLRdodSyRAU6OUCpPrxFKLbAH5i8PbyLgqGyehL0C3ME0ODMRWqGdXKpJp6mU/zfrGV92U93IX3Y06NC1RyapH/ll+G7yybvcwMQtZhA13N1JsU=
script: ./.jrl-ci/run build
after_success: ./.jrl-ci/run after_success
after_failure: ./.jrl-ci/run after_failure
before_install:
- export CMAKE_ADDITIONAL_OPTIONS="${CMAKE_ADDITIONAL_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
- ./.jrl-ci/run  before_install
